#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Apr 09 19:45:20 CST 2023
# SW Build 3671981 on Fri Oct 14 04:59:54 MDT 2022
#
# IP Build 3669848 on Fri Oct 14 08:30:02 MDT 2022
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# elaborate design
echo "xelab --incr --debug typical --relax --mt 32 -L xil_defaultlib -L secureip -L xpm --snapshot block_collision_tb_behav xil_defaultlib.block_collision_tb -log elaborate.log"
xelab --incr --debug typical --relax --mt 32 -L xil_defaultlib -L secureip -L xpm --snapshot block_collision_tb_behav xil_defaultlib.block_collision_tb -log elaborate.log

