# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gralerfics/MyFiles/Workspace/SUSTech-EE332-Digital-System-Designing-Project/ips/disp_buffer_0/disp_buffer_0.xci
# IP: The module: 'disp_buffer_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gralerfics/MyFiles/Workspace/SUSTech-EE332-Digital-System-Designing-Project/ips/disp_buffer_0/disp_buffer_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'disp_buffer_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/gralerfics/MyFiles/Workspace/SUSTech-EE332-Digital-System-Designing-Project/ips/disp_buffer_0/disp_buffer_0.xci
# IP: The module: 'disp_buffer_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gralerfics/MyFiles/Workspace/SUSTech-EE332-Digital-System-Designing-Project/ips/disp_buffer_0/disp_buffer_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'disp_buffer_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
