# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/test_clk_xdc.xdc

# IP: ip/vga_clock_generator/vga_clock_generator.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_clock_generator || ORIG_REF_NAME==vga_clock_generator} -quiet] -quiet
