# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gralerfics/MyFiles/Workspace/SUSTech-EE332-Digital-System-Designing-Project/ips/display_ram/display_ram.xci
# IP: The module: 'display_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gralerfics/MyFiles/Workspace/SUSTech-EE332-Digital-System-Designing-Project/ips/display_ram/display_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'display_ram'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/gralerfics/MyFiles/Workspace/SUSTech-EE332-Digital-System-Designing-Project/ips/display_ram/display_ram.xci
# IP: The module: 'display_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gralerfics/MyFiles/Workspace/SUSTech-EE332-Digital-System-Designing-Project/ips/display_ram/display_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'display_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
