# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/gralerfics/MyFiles/Workspace/SUSTech-EE332-Digital-System-Designing-Project/ips/oct_circle_rom/oct_circle_rom.xci
# IP: The module: 'oct_circle_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gralerfics/MyFiles/Workspace/SUSTech-EE332-Digital-System-Designing-Project/ips/oct_circle_rom/oct_circle_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'oct_circle_rom'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/gralerfics/MyFiles/Workspace/SUSTech-EE332-Digital-System-Designing-Project/ips/oct_circle_rom/oct_circle_rom.xci
# IP: The module: 'oct_circle_rom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/gralerfics/MyFiles/Workspace/SUSTech-EE332-Digital-System-Designing-Project/ips/oct_circle_rom/oct_circle_rom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'oct_circle_rom'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
