# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/src/xdc/top_module.xdc

# IP: C:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/display/vga_clk_generator/vga_clk_generator.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==vga_clk_generator || ORIG_REF_NAME==vga_clk_generator} -quiet] -quiet
