# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param general.maxThreads 32
set_param chipscope.maxJobs 3
set_param synth.incrementalSynthesisCache C:/Users/glver/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-16852-DESKTOP-6BOE7R7/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/project/project.cache/wt [current_project]
set_property parent.project_path C:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/project/project.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/project/project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/res/coe/vga_test.coe
read_vhdl -library xil_defaultlib {
  C:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/src/hdl/global/constants.vhd
  C:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/src/hdl/storage/bram_disp_controller.vhd
  C:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/src/hdl/vga/vga_controller.vhd
  C:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/src/hdl/vga/vga_timing_generator.vhd
  C:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/src/hdl/top_module.vhd
}
read_ip -quiet C:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/display/vga_clk_generator/vga_clk_generator.xci
set_property used_in_implementation false [get_files -all c:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/display/vga_clk_generator/vga_clk_generator_board.xdc]
set_property used_in_implementation false [get_files -all c:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/display/vga_clk_generator/vga_clk_generator.xdc]
set_property used_in_implementation false [get_files -all c:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/display/vga_clk_generator/vga_clk_generator_ooc.xdc]

read_ip -quiet C:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/ram/bram_disp/bram_disp.xci
set_property used_in_implementation false [get_files -all c:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/ram/bram_disp/bram_disp_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/src/xdc/top_module.xdc
set_property used_in_implementation false [get_files C:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/src/xdc/top_module.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top top_module -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_module.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
