# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/ram/ram_clk_generator/ram_clk_generator.xci
# IP: The module: 'ram_clk_generator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/ram/ram_clk_generator/ram_clk_generator_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_clk_generator'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/ram/ram_clk_generator/ram_clk_generator.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_clk_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/ram/ram_clk_generator/ram_clk_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_clk_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/ram/ram_clk_generator/ram_clk_generator.xci
# IP: The module: 'ram_clk_generator' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/ram/ram_clk_generator/ram_clk_generator_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_clk_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/ram/ram_clk_generator/ram_clk_generator.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_clk_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/ram/ram_clk_generator/ram_clk_generator_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ram_clk_generator'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
