# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/ram/bram_disp/bram_disp.xci
# IP: The module: 'bram_disp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/ram/bram_disp/bram_disp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_disp'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/ram/bram_disp/bram_disp.xci
# IP: The module: 'bram_disp' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/ram/bram_disp/bram_disp_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_disp'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
