# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/ram/bram_wall/bram_wall.xci
# IP: The module: 'bram_wall' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/ram/bram_wall/bram_wall_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_wall'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/ram/bram_wall/bram_wall.xci
# IP: The module: 'bram_wall' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Workplace/SUSTech-EE332-Digital-System-Designing-Project/ips/ram/bram_wall/bram_wall_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_wall'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
