connect_debug_port u_ila_0/probe3 [get_nets [list {p_view_targets[1][y][0]} {p_view_targets[1][y][1]} {p_view_targets[1][y][2]} {p_view_targets[1][y][3]} {p_view_targets[1][y][4]} {p_view_targets[1][y][5]} {p_view_targets[1][y][6]} {p_view_targets[1][y][7]} {p_view_targets[1][y][8]} {p_view_targets[1][y][9]} {p_view_targets[1][y][10]} {p_view_targets[1][y][11]} {p_view_targets[1][y][12]} {p_view_targets[1][y][13]} {p_view_targets[1][y][14]} {p_view_targets[1][y][15]} {p_view_targets[1][y][16]} {p_view_targets[1][y][17]} {p_view_targets[1][y][18]} {p_view_targets[1][y][19]}]]
connect_debug_port u_ila_0/probe4 [get_nets [list {p_view_targets[2][x][0]} {p_view_targets[2][x][1]} {p_view_targets[2][x][2]} {p_view_targets[2][x][3]} {p_view_targets[2][x][4]} {p_view_targets[2][x][5]} {p_view_targets[2][x][6]} {p_view_targets[2][x][7]} {p_view_targets[2][x][8]} {p_view_targets[2][x][9]} {p_view_targets[2][x][10]} {p_view_targets[2][x][11]} {p_view_targets[2][x][12]} {p_view_targets[2][x][13]} {p_view_targets[2][x][14]} {p_view_targets[2][x][15]} {p_view_targets[2][x][16]} {p_view_targets[2][x][17]} {p_view_targets[2][x][18]} {p_view_targets[2][x][19]}]]
connect_debug_port u_ila_0/probe5 [get_nets [list {p_view_targets[1][z][0]} {p_view_targets[1][z][1]} {p_view_targets[1][z][2]} {p_view_targets[1][z][3]} {p_view_targets[1][z][4]} {p_view_targets[1][z][5]} {p_view_targets[1][z][6]} {p_view_targets[1][z][7]} {p_view_targets[1][z][8]} {p_view_targets[1][z][9]} {p_view_targets[1][z][10]} {p_view_targets[1][z][11]} {p_view_targets[1][z][12]} {p_view_targets[1][z][13]} {p_view_targets[1][z][14]} {p_view_targets[1][z][15]} {p_view_targets[1][z][16]} {p_view_targets[1][z][17]} {p_view_targets[1][z][18]} {p_view_targets[1][z][19]}]]
connect_debug_port u_ila_0/probe6 [get_nets [list {p_view_targets[1][x][0]} {p_view_targets[1][x][1]} {p_view_targets[1][x][2]} {p_view_targets[1][x][3]} {p_view_targets[1][x][4]} {p_view_targets[1][x][5]} {p_view_targets[1][x][6]} {p_view_targets[1][x][7]} {p_view_targets[1][x][8]} {p_view_targets[1][x][9]} {p_view_targets[1][x][10]} {p_view_targets[1][x][11]} {p_view_targets[1][x][12]} {p_view_targets[1][x][13]} {p_view_targets[1][x][14]} {p_view_targets[1][x][15]} {p_view_targets[1][x][16]} {p_view_targets[1][x][17]} {p_view_targets[1][x][18]} {p_view_targets[1][x][19]}]]
connect_debug_port u_ila_0/probe7 [get_nets [list {p_view_targets[2][z][0]} {p_view_targets[2][z][1]} {p_view_targets[2][z][2]} {p_view_targets[2][z][3]} {p_view_targets[2][z][4]} {p_view_targets[2][z][5]} {p_view_targets[2][z][6]} {p_view_targets[2][z][7]} {p_view_targets[2][z][8]} {p_view_targets[2][z][9]} {p_view_targets[2][z][10]} {p_view_targets[2][z][11]} {p_view_targets[2][z][12]} {p_view_targets[2][z][13]} {p_view_targets[2][z][14]} {p_view_targets[2][z][15]} {p_view_targets[2][z][16]} {p_view_targets[2][z][17]} {p_view_targets[2][z][18]} {p_view_targets[2][z][19]}]]
connect_debug_port u_ila_0/probe8 [get_nets [list {p_view_targets[3][y][0]} {p_view_targets[3][y][1]} {p_view_targets[3][y][2]} {p_view_targets[3][y][3]} {p_view_targets[3][y][4]} {p_view_targets[3][y][5]} {p_view_targets[3][y][6]} {p_view_targets[3][y][7]} {p_view_targets[3][y][8]} {p_view_targets[3][y][9]} {p_view_targets[3][y][10]} {p_view_targets[3][y][11]} {p_view_targets[3][y][12]} {p_view_targets[3][y][13]} {p_view_targets[3][y][14]} {p_view_targets[3][y][15]} {p_view_targets[3][y][16]} {p_view_targets[3][y][17]} {p_view_targets[3][y][18]} {p_view_targets[3][y][19]}]]
connect_debug_port u_ila_0/probe9 [get_nets [list {p_view_targets[3][x][0]} {p_view_targets[3][x][1]} {p_view_targets[3][x][2]} {p_view_targets[3][x][3]} {p_view_targets[3][x][4]} {p_view_targets[3][x][5]} {p_view_targets[3][x][6]} {p_view_targets[3][x][7]} {p_view_targets[3][x][8]} {p_view_targets[3][x][9]} {p_view_targets[3][x][10]} {p_view_targets[3][x][11]} {p_view_targets[3][x][12]} {p_view_targets[3][x][13]} {p_view_targets[3][x][14]} {p_view_targets[3][x][15]} {p_view_targets[3][x][16]} {p_view_targets[3][x][17]} {p_view_targets[3][x][18]} {p_view_targets[3][x][19]}]]
connect_debug_port u_ila_0/probe10 [get_nets [list {p_view_targets[2][y][0]} {p_view_targets[2][y][1]} {p_view_targets[2][y][2]} {p_view_targets[2][y][3]} {p_view_targets[2][y][4]} {p_view_targets[2][y][5]} {p_view_targets[2][y][6]} {p_view_targets[2][y][7]} {p_view_targets[2][y][8]} {p_view_targets[2][y][9]} {p_view_targets[2][y][10]} {p_view_targets[2][y][11]} {p_view_targets[2][y][12]} {p_view_targets[2][y][13]} {p_view_targets[2][y][14]} {p_view_targets[2][y][15]} {p_view_targets[2][y][16]} {p_view_targets[2][y][17]} {p_view_targets[2][y][18]} {p_view_targets[2][y][19]}]]
connect_debug_port u_ila_0/probe11 [get_nets [list {p_view_targets[3][z][0]} {p_view_targets[3][z][1]} {p_view_targets[3][z][2]} {p_view_targets[3][z][3]} {p_view_targets[3][z][4]} {p_view_targets[3][z][5]} {p_view_targets[3][z][6]} {p_view_targets[3][z][7]} {p_view_targets[3][z][8]} {p_view_targets[3][z][9]} {p_view_targets[3][z][10]} {p_view_targets[3][z][11]} {p_view_targets[3][z][12]} {p_view_targets[3][z][13]} {p_view_targets[3][z][14]} {p_view_targets[3][z][15]} {p_view_targets[3][z][16]} {p_view_targets[3][z][17]} {p_view_targets[3][z][18]} {p_view_targets[3][z][19]}]]
connect_debug_port u_ila_0/probe14 [get_nets [list {pixel_scans[1][y][0]} {pixel_scans[1][y][1]} {pixel_scans[1][y][2]} {pixel_scans[1][y][3]} {pixel_scans[1][y][4]} {pixel_scans[1][y][5]} {pixel_scans[1][y][6]} {pixel_scans[1][y][7]} {pixel_scans[1][y][8]} {pixel_scans[1][y][9]} {pixel_scans[1][y][10]} {pixel_scans[1][y][11]} {pixel_scans[1][y][12]} {pixel_scans[1][y][13]} {pixel_scans[1][y][14]} {pixel_scans[1][y][15]} {pixel_scans[1][y][16]} {pixel_scans[1][y][17]} {pixel_scans[1][y][18]} {pixel_scans[1][y][19]}]]
connect_debug_port u_ila_0/probe15 [get_nets [list {pixel_scans[2][y][0]} {pixel_scans[2][y][1]} {pixel_scans[2][y][2]} {pixel_scans[2][y][3]} {pixel_scans[2][y][4]} {pixel_scans[2][y][5]} {pixel_scans[2][y][6]} {pixel_scans[2][y][7]} {pixel_scans[2][y][8]} {pixel_scans[2][y][9]} {pixel_scans[2][y][10]} {pixel_scans[2][y][11]} {pixel_scans[2][y][12]} {pixel_scans[2][y][13]} {pixel_scans[2][y][14]} {pixel_scans[2][y][15]} {pixel_scans[2][y][16]} {pixel_scans[2][y][17]} {pixel_scans[2][y][18]} {pixel_scans[2][y][19]}]]
connect_debug_port u_ila_0/probe16 [get_nets [list {pixel_scans[2][x][0]} {pixel_scans[2][x][1]} {pixel_scans[2][x][2]} {pixel_scans[2][x][3]} {pixel_scans[2][x][4]} {pixel_scans[2][x][5]} {pixel_scans[2][x][6]} {pixel_scans[2][x][7]} {pixel_scans[2][x][8]} {pixel_scans[2][x][9]} {pixel_scans[2][x][10]} {pixel_scans[2][x][11]} {pixel_scans[2][x][12]} {pixel_scans[2][x][13]} {pixel_scans[2][x][14]} {pixel_scans[2][x][15]} {pixel_scans[2][x][16]} {pixel_scans[2][x][17]} {pixel_scans[2][x][18]} {pixel_scans[2][x][19]}]]
connect_debug_port u_ila_0/probe17 [get_nets [list {pixel_scans[1][x][0]} {pixel_scans[1][x][1]} {pixel_scans[1][x][2]} {pixel_scans[1][x][3]} {pixel_scans[1][x][4]} {pixel_scans[1][x][5]} {pixel_scans[1][x][6]} {pixel_scans[1][x][7]} {pixel_scans[1][x][8]} {pixel_scans[1][x][9]} {pixel_scans[1][x][10]} {pixel_scans[1][x][11]} {pixel_scans[1][x][12]} {pixel_scans[1][x][13]} {pixel_scans[1][x][14]} {pixel_scans[1][x][15]} {pixel_scans[1][x][16]} {pixel_scans[1][x][17]} {pixel_scans[1][x][18]} {pixel_scans[1][x][19]}]]
connect_debug_port u_ila_0/probe18 [get_nets [list {pixel_scans[3][y][0]} {pixel_scans[3][y][1]} {pixel_scans[3][y][2]} {pixel_scans[3][y][3]} {pixel_scans[3][y][4]} {pixel_scans[3][y][5]} {pixel_scans[3][y][6]} {pixel_scans[3][y][7]} {pixel_scans[3][y][8]} {pixel_scans[3][y][9]} {pixel_scans[3][y][10]} {pixel_scans[3][y][11]} {pixel_scans[3][y][12]} {pixel_scans[3][y][13]} {pixel_scans[3][y][14]} {pixel_scans[3][y][15]} {pixel_scans[3][y][16]} {pixel_scans[3][y][17]} {pixel_scans[3][y][18]} {pixel_scans[3][y][19]}]]
connect_debug_port u_ila_0/probe19 [get_nets [list {pixel_scans[3][x][0]} {pixel_scans[3][x][1]} {pixel_scans[3][x][2]} {pixel_scans[3][x][3]} {pixel_scans[3][x][4]} {pixel_scans[3][x][5]} {pixel_scans[3][x][6]} {pixel_scans[3][x][7]} {pixel_scans[3][x][8]} {pixel_scans[3][x][9]} {pixel_scans[3][x][10]} {pixel_scans[3][x][11]} {pixel_scans[3][x][12]} {pixel_scans[3][x][13]} {pixel_scans[3][x][14]} {pixel_scans[3][x][15]} {pixel_scans[3][x][16]} {pixel_scans[3][x][17]} {pixel_scans[3][x][18]} {pixel_scans[3][x][19]}]]
connect_debug_port u_ila_0/probe27 [get_nets [list {tracer_colors[1][b][0]} {tracer_colors[1][b][1]} {tracer_colors[1][b][2]} {tracer_colors[1][b][3]}]]
connect_debug_port u_ila_0/probe30 [get_nets [list {tracer_colors[1][r][0]} {tracer_colors[1][r][1]} {tracer_colors[1][r][2]} {tracer_colors[1][r][3]}]]
connect_debug_port u_ila_0/probe31 [get_nets [list {tracer_colors[2][g][0]} {tracer_colors[2][g][1]} {tracer_colors[2][g][2]} {tracer_colors[2][g][3]}]]
connect_debug_port u_ila_0/probe32 [get_nets [list {tracer_colors[2][b][0]} {tracer_colors[2][b][1]} {tracer_colors[2][b][2]} {tracer_colors[2][b][3]}]]
connect_debug_port u_ila_0/probe33 [get_nets [list {tracer_colors[1][g][0]} {tracer_colors[1][g][1]} {tracer_colors[1][g][2]} {tracer_colors[1][g][3]}]]
connect_debug_port u_ila_0/probe34 [get_nets [list {tracer_colors[3][b][0]} {tracer_colors[3][b][1]} {tracer_colors[3][b][2]} {tracer_colors[3][b][3]}]]
connect_debug_port u_ila_0/probe35 [get_nets [list {tracer_colors[3][r][0]} {tracer_colors[3][r][1]} {tracer_colors[3][r][2]} {tracer_colors[3][r][3]}]]
connect_debug_port u_ila_0/probe36 [get_nets [list {tracer_colors[3][g][0]} {tracer_colors[3][g][1]} {tracer_colors[3][g][2]} {tracer_colors[3][g][3]}]]
connect_debug_port u_ila_0/probe37 [get_nets [list {update_colors[3]} {update_colors[2]} {update_colors[1]} {update_colors[0]}]]
connect_debug_port u_ila_0/probe38 [get_nets [list {tracer_colors[2][r][0]} {tracer_colors[2][r][1]} {tracer_colors[2][r][2]} {tracer_colors[2][r][3]}]]
connect_debug_port u_ila_0/probe39 [get_nets [list {tracer_writes[3]} {tracer_writes[2]} {tracer_writes[1]} {tracer_writes[0]}]]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 65536 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clk_sys_IBUF]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 17 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {map_read_addr[0]} {map_read_addr[1]} {map_read_addr[2]} {map_read_addr[3]} {map_read_addr[4]} {map_read_addr[5]} {map_read_addr[6]} {map_read_addr[7]} {map_read_addr[8]} {map_read_addr[9]} {map_read_addr[10]} {map_read_addr[11]} {map_read_addr[12]} {map_read_addr[13]} {map_read_addr[14]} {map_read_addr[15]} {map_read_addr[16]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 5 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {map_read_out[0]} {map_read_out[1]} {map_read_out[2]} {map_read_out[3]} {map_read_out[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 20 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {p_view_targets[0][x][0]} {p_view_targets[0][x][1]} {p_view_targets[0][x][2]} {p_view_targets[0][x][3]} {p_view_targets[0][x][4]} {p_view_targets[0][x][5]} {p_view_targets[0][x][6]} {p_view_targets[0][x][7]} {p_view_targets[0][x][8]} {p_view_targets[0][x][9]} {p_view_targets[0][x][10]} {p_view_targets[0][x][11]} {p_view_targets[0][x][12]} {p_view_targets[0][x][13]} {p_view_targets[0][x][14]} {p_view_targets[0][x][15]} {p_view_targets[0][x][16]} {p_view_targets[0][x][17]} {p_view_targets[0][x][18]} {p_view_targets[0][x][19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 20 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {p_view_targets[0][y][0]} {p_view_targets[0][y][1]} {p_view_targets[0][y][2]} {p_view_targets[0][y][3]} {p_view_targets[0][y][4]} {p_view_targets[0][y][5]} {p_view_targets[0][y][6]} {p_view_targets[0][y][7]} {p_view_targets[0][y][8]} {p_view_targets[0][y][9]} {p_view_targets[0][y][10]} {p_view_targets[0][y][11]} {p_view_targets[0][y][12]} {p_view_targets[0][y][13]} {p_view_targets[0][y][14]} {p_view_targets[0][y][15]} {p_view_targets[0][y][16]} {p_view_targets[0][y][17]} {p_view_targets[0][y][18]} {p_view_targets[0][y][19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 20 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {p_view_targets[0][z][0]} {p_view_targets[0][z][1]} {p_view_targets[0][z][2]} {p_view_targets[0][z][3]} {p_view_targets[0][z][4]} {p_view_targets[0][z][5]} {p_view_targets[0][z][6]} {p_view_targets[0][z][7]} {p_view_targets[0][z][8]} {p_view_targets[0][z][9]} {p_view_targets[0][z][10]} {p_view_targets[0][z][11]} {p_view_targets[0][z][12]} {p_view_targets[0][z][13]} {p_view_targets[0][z][14]} {p_view_targets[0][z][15]} {p_view_targets[0][z][16]} {p_view_targets[0][z][17]} {p_view_targets[0][z][18]} {p_view_targets[0][z][19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 20 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {pixel_scans[0][x][0]} {pixel_scans[0][x][1]} {pixel_scans[0][x][2]} {pixel_scans[0][x][3]} {pixel_scans[0][x][4]} {pixel_scans[0][x][5]} {pixel_scans[0][x][6]} {pixel_scans[0][x][7]} {pixel_scans[0][x][8]} {pixel_scans[0][x][9]} {pixel_scans[0][x][10]} {pixel_scans[0][x][11]} {pixel_scans[0][x][12]} {pixel_scans[0][x][13]} {pixel_scans[0][x][14]} {pixel_scans[0][x][15]} {pixel_scans[0][x][16]} {pixel_scans[0][x][17]} {pixel_scans[0][x][18]} {pixel_scans[0][x][19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 20 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {pixel_scans[0][y][0]} {pixel_scans[0][y][1]} {pixel_scans[0][y][2]} {pixel_scans[0][y][3]} {pixel_scans[0][y][4]} {pixel_scans[0][y][5]} {pixel_scans[0][y][6]} {pixel_scans[0][y][7]} {pixel_scans[0][y][8]} {pixel_scans[0][y][9]} {pixel_scans[0][y][10]} {pixel_scans[0][y][11]} {pixel_scans[0][y][12]} {pixel_scans[0][y][13]} {pixel_scans[0][y][14]} {pixel_scans[0][y][15]} {pixel_scans[0][y][16]} {pixel_scans[0][y][17]} {pixel_scans[0][y][18]} {pixel_scans[0][y][19]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 13 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {texture_read_addr[0]} {texture_read_addr[1]} {texture_read_addr[2]} {texture_read_addr[3]} {texture_read_addr[4]} {texture_read_addr[5]} {texture_read_addr[6]} {texture_read_addr[7]} {texture_read_addr[8]} {texture_read_addr[9]} {texture_read_addr[10]} {texture_read_addr[11]} {texture_read_addr[12]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 12 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {texture_read_out[0]} {texture_read_out[1]} {texture_read_out[2]} {texture_read_out[3]} {texture_read_out[4]} {texture_read_out[5]} {texture_read_out[6]} {texture_read_out[7]} {texture_read_out[8]} {texture_read_out[9]} {texture_read_out[10]} {texture_read_out[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 4 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {tracer_colors[0][b][0]} {tracer_colors[0][b][1]} {tracer_colors[0][b][2]} {tracer_colors[0][b][3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 4 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {tracer_colors[0][g][0]} {tracer_colors[0][g][1]} {tracer_colors[0][g][2]} {tracer_colors[0][g][3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 4 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {tracer_colors[0][r][0]} {tracer_colors[0][r][1]} {tracer_colors[0][r][2]} {tracer_colors[0][r][3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 17 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {write_buf_addr[0]} {write_buf_addr[1]} {write_buf_addr[2]} {write_buf_addr[3]} {write_buf_addr[4]} {write_buf_addr[5]} {write_buf_addr[6]} {write_buf_addr[7]} {write_buf_addr[8]} {write_buf_addr[9]} {write_buf_addr[10]} {write_buf_addr[11]} {write_buf_addr[12]} {write_buf_addr[13]} {write_buf_addr[14]} {write_buf_addr[15]} {write_buf_addr[16]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 12 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {write_buf_in[0]} {write_buf_in[1]} {write_buf_in[2]} {write_buf_in[3]} {write_buf_in[4]} {write_buf_in[5]} {write_buf_in[6]} {write_buf_in[7]} {write_buf_in[8]} {write_buf_in[9]} {write_buf_in[10]} {write_buf_in[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list map_read_tick]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list pulse]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list texture_read_tick]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list tracer_idle_all]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list tracer_start]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list tracer_writes]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list update_colors]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list write_buf_tick]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 65536 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list clk_vga_gen/inst/clkfbout_buf_clk_vga_generator]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 17 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {read_buf_addr[0]} {read_buf_addr[1]} {read_buf_addr[2]} {read_buf_addr[3]} {read_buf_addr[4]} {read_buf_addr[5]} {read_buf_addr[6]} {read_buf_addr[7]} {read_buf_addr[8]} {read_buf_addr[9]} {read_buf_addr[10]} {read_buf_addr[11]} {read_buf_addr[12]} {read_buf_addr[13]} {read_buf_addr[14]} {read_buf_addr[15]} {read_buf_addr[16]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 12 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {read_buf_out[0]} {read_buf_out[1]} {read_buf_out[2]} {read_buf_out[3]} {read_buf_out[4]} {read_buf_out[5]} {read_buf_out[6]} {read_buf_out[7]} {read_buf_out[8]} {read_buf_out[9]} {read_buf_out[10]} {read_buf_out[11]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 1 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list clk_sys_IBUF]]
create_debug_core u_ila_2 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_2]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_2]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_2]
set_property C_DATA_DEPTH 65536 [get_debug_cores u_ila_2]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_2]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_2]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_2]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_2]
set_property port_width 1 [get_debug_ports u_ila_2/clk]
connect_debug_port u_ila_2/clk [get_nets [list clk_vga_gen/inst/clk_vga]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_2/probe0]
set_property port_width 1 [get_debug_ports u_ila_2/probe0]
connect_debug_port u_ila_2/probe0 [get_nets [list read_buf_tick]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clk_vga]
